#!/usr/bin/env python3
import os
import crypt

# Generated by Anthropic Claude.

def create_userconf(boot_path, username, password):
    """
    Create userconf.txt in the boot partition
    """
    try:
        # Generate SHA-512 password hash
        password_hash = crypt.crypt(password, crypt.mksalt(crypt.METHOD_SHA512))

        # Create userconf.txt
        userconf_path = os.path.join(boot_path, 'userconf.txt')
        with open(userconf_path, 'w') as f:
            f.write(f'{username}:{password_hash}')

        print(f"Created userconf.txt for user '{username}'")

    except Exception as e:
        print(f"Error creating userconf.txt: {e}")
        raise

def main():
    BOOT_PATH = "/mnt/part1"
    USERNAME = "pi"
    PASSWORD = "raspberry"

    try:
        create_userconf(BOOT_PATH, USERNAME, PASSWORD)
        print("Successfully created userconf.txt")
    except Exception as e:
        print(f"Failed to create userconf.txt: {e}")
        exit(1)

if __name__ == "__main__":
    main()
