#!/usr/bin/env python3
import os

# Generated by Anthropic Claude.

def enable_ssh_service(rootfs_path):
    """
    Enable SSH service in root filesystem
    """
    try:
        # Create the symlink for SSH service
        service_path = os.path.join(
            rootfs_path, 'etc/systemd/system/multi-user.target.wants')
        ssh_service = 'ssh.service'
        ssh_service_link = os.path.join(service_path, ssh_service)
        ssh_service_target = os.path.join(
            '/', 'lib', 'systemd', 'system', ssh_service)

        # Create systemd symlink if it doesn't exist
        if not os.path.exists(ssh_service_link):
            os.makedirs(service_path, exist_ok=True)
            os.symlink(ssh_service_target, ssh_service_link)
            print(f"Enabled SSH service in root filesystem")
        else:
            print("SSH service already enabled in root filesystem")

    except Exception as e:
        print(f"Error enabling SSH service: {e}")

def main():
    ROOTFS_PATH = "/mnt/part2"

    try:
        enable_ssh_service(ROOTFS_PATH)
        print("SSH configuration completed successfully")
    except Exception as e:
        print(f"Error configuring SSH: {e}")

if __name__ == "__main__":
    main()
