#!/usr/bin/env python3
import os
import shutil
import re

# Generated by Anthropic Claude.

def modify_swap_size(rootfs_path, new_size):
    """
    Modify the CONF_SWAPSIZE in /etc/dphys-swapfile

    Args:
        rootfs_path: Path to the mounted root filesystem
        new_size: New swap size in MB
    """
    swap_file = os.path.join(rootfs_path, 'etc/dphys-swapfile')
    backup_file = swap_file + '.bak'

    if not os.path.exists(swap_file):
        raise FileNotFoundError(f"Swap configuration file not found at {swap_file}")

    # Create backup
    shutil.copy2(swap_file, backup_file)

    # Read the current content
    with open(swap_file, 'r') as f:
        content = f.read()

    # Replace the CONF_SWAPSIZE line
    # This will handle both commented and uncommented lines
    new_content = re.sub(
        r'^#?CONF_SWAPSIZE=.*$',
        f'CONF_SWAPSIZE={new_size}',
        content,
        flags=re.MULTILINE
    )

    # Write the modified content
    with open(swap_file, 'w') as f:
        f.write(new_content)

    print(f"Successfully modified swap size to {new_size}MB")
    print(f"Backup saved as {backup_file}")

def main():
    ROOTFS_PATH = "/mnt/part2"
    NEW_SWAP_SIZE = 1024  # Size in MB

    try:
        modify_swap_size(ROOTFS_PATH, NEW_SWAP_SIZE)
    except Exception as e:
        print(f"Error modifying swap size: {e}")

if __name__ == "__main__":
    main()
