unstable_features = true
max_width = 80
comment_width = 80
wrap_comments = true
normalize_comments = true
format_code_in_doc_comments = true
fn_call_width = 80
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
error_on_line_overflow = true
error_on_unformatted = true